baseURL = "https://agonist.github.io/mc/"
languageCode = "en-us"
title = "Martabak Cult Engineering"
theme = "m10c"

[params]
  author = "Martabak Cult"
  description = "Code offering for the Martabak god"
